apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: quarkus-component-e2e-urrzdpdfzz
  namespace: has-e2e-d10443ad-62c7-4c71-aa27-49d69fc0a8a3
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: pet-clinic-e2e-hqpzwnstvo
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: quarkus-component-e2e-urrzdpdfzz
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: quarkus-component-e2e-urrzdpdfzz-
      labels:
        build.appstudio.openshift.io/application: pet-clinic-e2e-hqpzwnstvo
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: quarkus-component-e2e-urrzdpdfzz
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: has-e2e-d10443ad-62c7-4c71-aa27-49d69fc0a8a3
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:has-e2e-d10443ad-62c7-4c71-aa27-49d69fc0a8a3-quarkus-component-e2e-urrzdpdfzz-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/redhat-appstudio-qe/devfile-sample-code-with-quarkus/main/src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: ./
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: quarkus-component-e2e-urrzdpdfzz/$(tt.params.git-revision)
    status: {}
status: {}
